# Generated by Django 4.2.18 on 2025-04-07 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_alter_br_cataleg_ptr_alter_categoria_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplar',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.centre'),
        ),
    ]
