# Generated by Django 4.2.18 on 2025-04-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_exemplar_centre'),
        ('biblioteca', '0007_usuari_telefon'),
    ]

    operations = [
    ]
