# Generated by Django 4.2.18 on 2025-04-08 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_merge_0007_exemplar_centre_0007_usuari_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplar',
            name='exclos_prestec',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='telefon',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='El número de telèfon ha de tenir exactament 9 dígits numèrics.', regex='^\\d{9}$')]),
        ),
    ]
