# Generated by Django 4.2.18 on 2025-04-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_alter_exemplar_exclos_prestec_alter_usuari_telefon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cicle',
            new_name='Grup',
        ),
        migrations.RenameField(
            model_name='usuari',
            old_name='cicle',
            new_name='grup',
        ),
    ]
