# Generated by Django 4.2.18 on 2025-05-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_rename_cicle_grup_rename_cicle_usuari_grup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestec',
            name='data_prestec',
            field=models.DateField(blank=True, null=True),
        ),
    ]
